"""Bloomberg yellow-key exchange code → listing country (ISO 3166-1 alpha-2).

Not an industry axis. Unlisted codes stay unmapped; do not guess.
"""
from __future__ import annotations

ASSET_CLASS = frozenset(
    {
        "Equity",
        "Corp",
        "Pfd",
        "Govt",
        "Muni",
        "Mtge",
        "Index",
        "Comdty",
        "Curncy",
        "M-Mkt",
    }
)

# Yellow-key composite / venue → listing ISO. CN is Canada; CH is China Shanghai; IT is Israel.
EXCHANGE_TO_ISO = {
    "US": "US",
    "UN": "US",
    "UW": "US",
    "UA": "US",
    "UP": "US",
    "UQ": "US",
    "UR": "US",
    "UF": "US",
    "UV": "US",
    "PK": "US",
    "CH": "CN",
    "CS": "CN",
    "CN": "CA",
    "CT": "CA",
    "CV": "CA",
    "JP": "JP",
    "JT": "JP",
    "KS": "KR",
    "KQ": "KR",
    "KF": "KR",
    "HK": "HK",
    "TT": "TW",
    "AU": "AU",
    "AT": "AU",
    "VN": "VN",
    "LN": "GB",
    "LI": "GB",
    "MK": "MY",
    "SS": "SE",
    "GR": "DE",
    "GY": "DE",
    "TB": "TH",
    "IJ": "ID",
    "FP": "FR",
    "PW": "PL",
    "RU": "RU",
    "RM": "RU",
    "SP": "SG",
    "UZ": "UA",
    "IM": "IT",
    "TI": "TR",
    "IT": "IL",
    "MB": "MD",
    "BZ": "BR",
    "SW": "CH",
    "VX": "CH",
    "NO": "NO",
    "RO": "RO",
    "SM": "ES",
    "AB": "SA",
    "BD": "BD",
    "SG": "RS",
    "IE": "IR",
    "IR": "IR",
    "NK": "NP",
    "PM": "PH",
    "SL": "LK",
    "SJ": "ZA",
    "MM": "MX",
    "BB": "BE",
    "DC": "DK",
    "FH": "FI",
    "NA": "NL",
    "NZ": "NZ",
    "PL": "PT",
    "ID": "IE",
    "GA": "GR",
    "KK": "KW",
    "UH": "AE",
    "ME": "AE",
    "DU": "AE",
    "CB": "CO",
    "OM": "OM",
    "AR": "AR",
    "AV": "AT",
    "CZ": "CZ",
    "CP": "CZ",
    "KZ": "KZ",
    "AZ": "AZ",
    "TU": "TN",
    "HB": "HU",
    "KN": "KE",
    "QD": "QA",
    "LX": "LU",
    "CI": "CL",
    "PE": "PE",
    "PA": "PE",
    "EY": "EG",
    "JR": "JO",
    "MO": "MA",
    "MC": "MA",
    "CY": "CY",
    "IQ": "IQ",
    "JA": "JM",
    "SK": "SK",
    "GG": "GE",
    "BI": "BH",
    "PS": "PS",
    "PP": "PG",
    "PN": "PA",
    "ET": "ET",
    "BC": "BS",
    "GN": "GN",
    "MV": "MV",
    "BG": "BG",
    "BH": "BH",
    "SY": "SY",
    "TZ": "TZ",
    "UG": "UG",
    "MZ": "MZ",
    "RW": "RW",
    "UY": "UY",
    "CR": "CR",
    "LB": "LB",
    "KH": "KH",
    "BM": "BM",
    "MX": "MX",
    "KY": "KY",
    "BA": "BA",
    "AL": "AL",
    "HO": "HN",
    "NL": "NG",
    "MS": "EG",
    "BU": "BG",
    "BT": "BW",
    "BK": "TH",
    "ZH": "CN",
    "ZU": "CN",
    "S3": "SA",
    "TP": "PT",
    "EL": "GR",
    "LH": "LT",
    "LR": "LR",
    "HM": "SA",
    "FS": "DE",
    "NW": "DE",
    "AX": "AU",
    "DE": "DE",
    "ES": "ES",
}

COUNTRY_LABEL = {
    "US": "United States",
    "CN": "China",
    "CA": "Canada",
    "IN": "India",
    "JP": "Japan",
    "KR": "Korea",
    "HK": "Hong Kong",
    "TW": "Taiwan",
    "AU": "Australia",
    "VN": "Vietnam",
    "GB": "United Kingdom",
    "MY": "Malaysia",
    "SE": "Sweden",
    "DE": "Germany",
    "TH": "Thailand",
    "ID": "Indonesia",
    "FR": "France",
    "PL": "Poland",
    "RU": "Russia",
    "SG": "Singapore",
    "UA": "Ukraine",
    "IT": "Italy",
    "TR": "Turkey",
    "IL": "Israel",
    "MD": "Moldova",
    "BR": "Brazil",
    "CH": "Switzerland",
    "NO": "Norway",
    "RO": "Romania",
    "ES": "Spain",
    "SA": "Saudi Arabia",
    "BD": "Bangladesh",
    "RS": "Serbia",
    "IR": "Iran",
    "NP": "Nepal",
    "PH": "Philippines",
    "LK": "Sri Lanka",
    "ZA": "South Africa",
    "MX": "Mexico",
    "BE": "Belgium",
    "DK": "Denmark",
    "FI": "Finland",
    "NL": "Netherlands",
    "NZ": "New Zealand",
    "PT": "Portugal",
    "IE": "Ireland",
    "GR": "Greece",
    "KW": "Kuwait",
    "AE": "United Arab Emirates",
    "CO": "Colombia",
    "OM": "Oman",
    "AR": "Argentina",
    "AT": "Austria",
    "CZ": "Czechia",
    "KZ": "Kazakhstan",
    "AZ": "Azerbaijan",
    "TN": "Tunisia",
    "HU": "Hungary",
    "KE": "Kenya",
    "QA": "Qatar",
    "LU": "Luxembourg",
    "CL": "Chile",
    "PE": "Peru",
    "EG": "Egypt",
    "JO": "Jordan",
    "MA": "Morocco",
    "CY": "Cyprus",
    "IQ": "Iraq",
    "JM": "Jamaica",
    "SK": "Slovakia",
    "GE": "Georgia",
    "BH": "Bahrain",
    "PS": "Palestine",
    "PG": "Papua New Guinea",
    "PA": "Panama",
    "ET": "Ethiopia",
    "BS": "Bahamas",
    "GN": "Guinea",
    "MV": "Maldives",
    "BG": "Bulgaria",
    "SY": "Syria",
    "TZ": "Tanzania",
    "UG": "Uganda",
    "MZ": "Mozambique",
    "RW": "Rwanda",
    "UY": "Uruguay",
    "CR": "Costa Rica",
    "LB": "Lebanon",
    "KH": "Cambodia",
    "BM": "Bermuda",
    "KY": "Cayman Islands",
    "BA": "Bosnia",
    "AL": "Albania",
    "HN": "Honduras",
    "NG": "Nigeria",
    "BW": "Botswana",
    "LT": "Lithuania",
    "LR": "Liberia",
}


def parse_ticker(ticker: str) -> dict:
    raw = (ticker or "").strip()
    parts = raw.split()
    exch = ""
    if len(parts) >= 2:
        exch = parts[-2].upper() if parts[-1] in ASSET_CLASS else parts[-1].upper()
    iso = EXCHANGE_TO_ISO.get(exch) if exch else None
    return {
        "exchangeCode": exch or None,
        "listingCountry": iso,
        "listingCountryUnmapped": not bool(iso),
        "listingCountryLabel": COUNTRY_LABEL.get(iso or "", "Unmapped") if iso else "Unmapped",
    }


def country_label(iso: str | None) -> str:
    if not iso or iso == "UNMAPPED":
        return "Unmapped"
    return COUNTRY_LABEL.get(iso, iso)
